export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'refactor',
        'test',
        'chore',
        'ci',
        'perf',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'auth',
        'catalog',
        'search',
        'docs',
        'rbac',
        'infra',
        'api',
        'frontend',
        'admin',
        'audit',
        'tooling',
        'deps',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'subject-full-stop': [2, 'never', '.'],
    'header-max-length': [2, 'always', 72],
  },
};
