-- Migration: 202507161300_Docs_DocumentationAndHistory
-- Documentation és DocumentationHistory táblák

CREATE TABLE "Documentations" (
    "Id"            SERIAL PRIMARY KEY,
    "ApplicationId" INTEGER NOT NULL,
    "Title"         VARCHAR(500) NOT NULL,
    "Content"       TEXT NOT NULL,
    "Type"          VARCHAR(50) NOT NULL,
    "Status"        VARCHAR(50) NOT NULL,
    "Version"       INTEGER NOT NULL DEFAULT 1,
    "CreatedAt"     TIMESTAMPTZ NOT NULL,
    "UpdatedAt"     TIMESTAMPTZ NOT NULL,
    "AuthorUserId"  INTEGER,
    CONSTRAINT "FK_Documentations_Applications_ApplicationId"
        FOREIGN KEY ("ApplicationId") REFERENCES "Applications"("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Documentations_Users_AuthorUserId"
        FOREIGN KEY ("AuthorUserId") REFERENCES "Users"("Id") ON DELETE SET NULL
);

CREATE TABLE "DocumentationHistories" (
    "Id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DocumentationId"   INTEGER NOT NULL,
    "Content"           TEXT NOT NULL,
    "Version"           INTEGER NOT NULL,
    "ArchivedAt"        TIMESTAMPTZ NOT NULL,
    "ArchivedByUserId"  INTEGER,
    CONSTRAINT "FK_DocumentationHistories_Documentations_DocumentationId"
        FOREIGN KEY ("DocumentationId") REFERENCES "Documentations"("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Documentations_ApplicationId"   ON "Documentations"("ApplicationId");
CREATE INDEX "IX_Documentations_AuthorUserId"     ON "Documentations"("AuthorUserId");
CREATE INDEX "IX_Documentations_Type"             ON "Documentations"("Type");
CREATE INDEX "IX_Documentations_Status"           ON "Documentations"("Status");

CREATE INDEX "IX_DocumentationHistories_DocumentationId"
    ON "DocumentationHistories"("DocumentationId");
CREATE UNIQUE INDEX "IX_DocumentationHistories_DocumentationId_Version"
    ON "DocumentationHistories"("DocumentationId", "Version");

-- Rollback:
-- DROP TABLE "DocumentationHistories";
-- DROP TABLE "Documentations";
