-- Migration: 20250618120000_Auth_InitialSchema
-- Description: Create auth and RBAC tables with system role seed data

BEGIN;

-- Users
CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DisplayName" character varying(200) NOT NULL,
    "Email" character varying(320) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "LastLogin" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

-- Roles
CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "IsSystemRole" boolean NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");

INSERT INTO "Roles" ("Id", "Name", "Description", "IsSystemRole") VALUES
    (1, 'Admin', 'Full system access', true),
    (2, 'Developer', 'Developer access to applications and documentation', true),
    (3, 'ApplicationOwner', 'Manage owned applications', true),
    (4, 'ReadOnly', 'Read-only access', true);

-- Permissions
CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "ResourceType" character varying(100) NOT NULL,
    "Action" character varying(100) NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");

-- ExternalIdentities
CREATE TABLE "ExternalIdentities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ProviderType" character varying(50) NOT NULL,
    "ExternalId" character varying(500) NOT NULL,
    "ExternalGroupsJson" text,
    "LastSyncedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExternalIdentities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExternalIdentities_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_ExternalIdentities_ProviderType_ExternalId"
    ON "ExternalIdentities" ("ProviderType", "ExternalId");
CREATE INDEX "IX_ExternalIdentities_UserId" ON "ExternalIdentities" ("UserId");

-- LocalCredentials
CREATE TABLE "LocalCredentials" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PasswordHash" text NOT NULL,
    "MustChangePassword" boolean NOT NULL DEFAULT true,
    "FailedAttempts" integer NOT NULL DEFAULT 0,
    "LockedUntil" timestamp with time zone,
    "PasswordUpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LocalCredentials" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LocalCredentials_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_LocalCredentials_UserId" ON "LocalCredentials" ("UserId");

-- RolePermissions
CREATE TABLE "RolePermissions" (
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermissions_Roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId"
        FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");

-- UserRoles
CREATE TABLE "UserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "GrantedByUserId" integer,
    "GrantedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "Source" character varying(50) NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

-- GroupRoleMappings
CREATE TABLE "GroupRoleMappings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProviderType" character varying(50) NOT NULL,
    "ExternalGroupRef" character varying(500) NOT NULL,
    "RoleId" integer NOT NULL,
    "Description" character varying(500),
    "IsActive" boolean NOT NULL DEFAULT true,
    CONSTRAINT "PK_GroupRoleMappings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupRoleMappings_Roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_GroupRoleMappings_RoleId" ON "GroupRoleMappings" ("RoleId");

COMMIT;
