-- Migration: 20250618120000_Auth_InitialSchema
-- Auth/RBAC initial schema: Users, ExternalIdentities, LocalCredentials,
-- Roles, Permissions, RolePermissions, UserRoles, GroupRoleMappings
-- Seed: system roles (Admin, Developer, ApplicationOwner, ReadOnly)

START TRANSACTION;

-- =============================================
-- Tables
-- =============================================

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DisplayName" character varying(200) NOT NULL,
    "Email" character varying(320) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "LastLogin" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500),
    "IsSystemRole" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "ResourceType" character varying(100) NOT NULL,
    "Action" character varying(100) NOT NULL,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);

CREATE TABLE "ExternalIdentities" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ProviderType" character varying(50) NOT NULL,
    "ExternalId" character varying(500) NOT NULL,
    "ExternalGroupsJson" text,
    "LastSyncedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExternalIdentities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExternalIdentities_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "LocalCredentials" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PasswordHash" text NOT NULL,
    "MustChangePassword" boolean NOT NULL DEFAULT TRUE,
    "FailedAttempts" integer NOT NULL DEFAULT 0,
    "LockedUntil" timestamp with time zone,
    "PasswordUpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_LocalCredentials" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LocalCredentials_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RolePermissions" (
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
    CONSTRAINT "FK_RolePermissions_Roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId"
        FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    "GrantedByUserId" integer,
    "GrantedAt" timestamp with time zone NOT NULL,
    "Source" character varying(50) NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "GroupRoleMappings" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProviderType" character varying(50) NOT NULL,
    "ExternalGroupRef" character varying(500) NOT NULL,
    "RoleId" integer NOT NULL,
    "Description" character varying(500),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_GroupRoleMappings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_GroupRoleMappings_Roles_RoleId"
        FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

-- =============================================
-- Indexes
-- =============================================

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");
CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");
CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");
CREATE INDEX "IX_ExternalIdentities_UserId" ON "ExternalIdentities" ("UserId");
CREATE UNIQUE INDEX "IX_ExternalIdentities_ProviderType_ExternalId" ON "ExternalIdentities" ("ProviderType", "ExternalId");
CREATE UNIQUE INDEX "IX_LocalCredentials_UserId" ON "LocalCredentials" ("UserId");
CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");
CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX "IX_GroupRoleMappings_RoleId" ON "GroupRoleMappings" ("RoleId");
CREATE UNIQUE INDEX "IX_GroupRoleMappings_ProviderType_ExternalGroupRef_RoleId" ON "GroupRoleMappings" ("ProviderType", "ExternalGroupRef", "RoleId");

-- =============================================
-- Seed: system roles
-- =============================================

INSERT INTO "Roles" ("Id", "Name", "Description", "IsSystemRole")
VALUES
    (1, 'Admin', 'Full access; user management, group mappings, all CRUD', TRUE),
    (2, 'Developer', 'Application CRUD, developer/ops docs read and write', TRUE),
    (3, 'ApplicationOwner', 'Edit own applications, write user docs', TRUE),
    (4, 'ReadOnly', 'Read all public content (user docs, catalog)', TRUE);

SELECT setval('"Roles_Id_seq"', 4);

COMMIT;
