-- Migration: 20250624120000_Catalog_ApplicationSchema
-- Catalog domain: Applications, ApplicationEnvironments, ApplicationContacts,
-- Tags, ApplicationTags

START TRANSACTION;

-- =============================================
-- Tables
-- =============================================

CREATE TABLE "Tags" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Color" character varying(7),
    CONSTRAINT "PK_Tags" PRIMARY KEY ("Id")
);

CREATE TABLE "Applications" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(200) NOT NULL,
    "ShortDescription" character varying(500) NOT NULL,
    "DetailedDescription" character varying(4000),
    "Status" character varying(50) NOT NULL,
    "Type" character varying(50) NOT NULL,
    "OwnerTeam" character varying(200) NOT NULL,
    "SourceControl" character varying(50) NOT NULL DEFAULT 'None',
    "RepositoryUrl" character varying(2000),
    "WikiUrl" character varying(2000),
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CreatedByUserId" integer,
    CONSTRAINT "PK_Applications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Applications_Users_CreatedByUserId"
        FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);

CREATE TABLE "ApplicationContacts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationId" integer NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Value" character varying(500) NOT NULL,
    "Label" character varying(200),
    CONSTRAINT "PK_ApplicationContacts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApplicationContacts_Applications_ApplicationId"
        FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ApplicationEnvironments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ApplicationId" integer NOT NULL,
    "Type" character varying(50) NOT NULL,
    "Url" character varying(2000) NOT NULL,
    "Notes" character varying(500),
    "IsPublic" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_ApplicationEnvironments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ApplicationEnvironments_Applications_ApplicationId"
        FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ApplicationTags" (
    "ApplicationId" integer NOT NULL,
    "TagId" integer NOT NULL,
    CONSTRAINT "PK_ApplicationTags" PRIMARY KEY ("ApplicationId", "TagId"),
    CONSTRAINT "FK_ApplicationTags_Applications_ApplicationId"
        FOREIGN KEY ("ApplicationId") REFERENCES "Applications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ApplicationTags_Tags_TagId"
        FOREIGN KEY ("TagId") REFERENCES "Tags" ("Id") ON DELETE CASCADE
);

-- =============================================
-- Indexes
-- =============================================

CREATE UNIQUE INDEX "IX_Applications_Name" ON "Applications" ("Name");
CREATE INDEX "IX_Applications_OwnerTeam" ON "Applications" ("OwnerTeam");
CREATE INDEX "IX_Applications_Status" ON "Applications" ("Status");
CREATE INDEX "IX_Applications_IsDeleted" ON "Applications" ("IsDeleted");
CREATE INDEX "IX_Applications_CreatedByUserId" ON "Applications" ("CreatedByUserId");
CREATE INDEX "IX_ApplicationContacts_ApplicationId" ON "ApplicationContacts" ("ApplicationId");
CREATE INDEX "IX_ApplicationEnvironments_ApplicationId" ON "ApplicationEnvironments" ("ApplicationId");
CREATE INDEX "IX_ApplicationTags_TagId" ON "ApplicationTags" ("TagId");
CREATE UNIQUE INDEX "IX_Tags_Name" ON "Tags" ("Name");

COMMIT;
