-- Migration: 202507161400_Audit_AuditLog
-- Audit napló tábla

CREATE TABLE "AuditLogs" (
    "Id"            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"        INTEGER,
    "Action"        VARCHAR(100) NOT NULL,
    "ResourceType"  VARCHAR(100) NOT NULL,
    "ResourceId"    VARCHAR(100) NOT NULL,
    "OldValueJson"  TEXT,
    "NewValueJson"  TEXT,
    "IpAddress"     VARCHAR(45),
    "UserAgent"     VARCHAR(500),
    "Timestamp"     TIMESTAMPTZ NOT NULL
);

CREATE INDEX "IX_AuditLogs_Timestamp"              ON "AuditLogs"("Timestamp");
CREATE INDEX "IX_AuditLogs_UserId"                 ON "AuditLogs"("UserId");
CREATE INDEX "IX_AuditLogs_ResourceType_ResourceId" ON "AuditLogs"("ResourceType", "ResourceId");

-- Rollback:
-- DROP TABLE "AuditLogs";
