// <auto-generated />
using System;
using AppInventory.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable enable

namespace AppInventory.Infrastructure.Data.Migrations;

[DbContext(typeof(AppInventoryDbContext))]
[Migration("20250618120000_Auth_InitialSchema")]
partial class Auth_InitialSchema
{
}
